### ISSUE TITLE
项目还在维护吗？有适配spring boot 3的打算吗

### ISSUE THREAD

**Issue by WangJincheng4869** [raodv/captcha#171]
项目还在维护吗？有适配spring boot 3的打算吗

**Comment by gm100861** [comment]
官网都打不开了,估计是不维护了.

**Comment by WangJincheng4869** [comment]
> 官网都打不开了,估计是不维护了.

哎~ 八成是凉了，所以找了个替代品  [[tianai-captcha](https://github.com/tianaiyouqing/tianai-captcha)](https://github.com/tianaiyouqing/tianai-captcha)

**Comment by softboy99** [comment]
gitee上 dev分支一个月前有人提交代码，也有人适配了springboot3,但没人Merge

**Comment by liusuizhu** [comment]
我已经重写了这个项目，适配springboot3
