### ISSUE TITLE
你好，是否可以支持png以外的图片格式？

### ISSUE THREAD

**Issue by zzzmhcn** [raodv/captcha#38]
本人学艺不精，万一说错还请见谅
java部分代码中发现，getResourcesImagesFile，等方法，都写死了png格式。
我能理解那一小块拼图必须是png，但好像没必要2类原图也都是png
考虑到现在云主机的带宽贵到起飞，png压缩后也要30kb+  , jpg可以压缩到8kb+ 用户同时并发访问多的时候，不容易出现默认底图，用户不容易流失在这一步。

**Comment by raodv** [comment]
欢迎提交PR

**Comment by zzzmhcn** [comment]
你好，我是github小白，不太明白什么pr，这个问题先放一放，我发现一个更严重的问题
我用的是弹出 拼图，已发布线上，我发现每次用户完成拼图，一共会调用3次get接口，而且原本png一张图是100kb，相当于一个人滑一次要消耗300kb流量，所以之前才发生了用户访问非常慢，拼图界面要先卡在默认图片很久才出图。
我最终自己注释了一小部分代码
例如 canvasClick 和 end 下的 reqCheck方法有一个setTimeout调用了this.refresh();
我猜想这样设计可能是为了，用户下次再来可以不用请求刷新？但其实用户已经成功了就不需要再次刷新了。

特地来提一下还是希望这个项目能更完美
哈哈哈
总之我还是要感谢作者大佬，提供了一个可以免费使用的方案，帮助了我这种没人访问的小破站反爬虫的可能性。

**Comment by raodv** [comment]
get请求是由前端js控制的，是可以自己设置的。一般check校验成功就会直接跳转业务逻辑了，不会再调用了。

**Comment by zzzmhcn** [comment]
你好，我这里用的是目前github最新版，确实会调用3次get请求
具体代码流程是这样的

首先VerifyPoints.vue
reqGe方法t对应的就是axios的请求 '/captcha/get' 接口
然后在方法getPictrue调用了reqGet
然后在refresh调用了getPictrue
然后在canvasClick -> reqCheck -> settimeout 里调用了refresh 因此会请求 '/captcha/get' 接口

然后VerifySlide.vue
end -> reqCheck -> settimeout -> refresh 同上


至于为什么是3次我已经不记得了，只是昨天顺手改的，现在改完已经是一次了
